### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: invalid number or unquoted string near <!DOCTYPE html PUBLIC "-//W3C

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tijanibro/mchoice-applications#4]
```
What steps will reproduce the problem?
1. Started Simulator
2. Then Followed exact steps mentioned in this URL 
(http://code.google.com/p/mchoice-applications/wiki/JavaGuide#USSD_Guide)
3. Sent message through simulator with following data
App URL=http://localhost:8080/USSD
Phone #=8888308128
Message=*124#

What is the expected output? What do you see instead?

Expected:      Simulator gets back response from Server

Observed:      

              exception
com.google.gson.JsonSyntaxException: 
com.google.gson.stream.MalformedJsonException: invalid number or unquoted 
string near <!DOCTYPE html PUBLIC "-//W3C
    at com.google.gson.Streams.parse(Streams.java:51)
    at com.google.gson.Gson.fromJson(Gson.java:514)
    at com.google.gson.Gson.fromJson(Gson.java:484)
    at com.google.gson.Gson.fromJson(Gson.java:434)
    at com.google.gson.Gson.fromJson(Gson.java:406)
    at hms.sdp.ussd.client.MchoiceUssdSender.sendMessage(MchoiceUssdSender.java:123)
    at hms.sdp.ussd.client.MchoiceUssdSender.sendMessage(MchoiceUssdSender.java:140)
    at demo.MessageReceiver.onMessage(MessageReceiver.java:22)
    at hms.sdp.ussd.client.MchoiceUssdReceiver.doPost(MchoiceUssdReceiver.java:52)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: invalid number or 
unquoted string near <!DOCTYPE html PUBLIC "-//W3C
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1110)
    at com.google.gson.stream.JsonReader.decodeLiteral(JsonReader.java:1100)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:343)
    at com.google.gson.Streams.parse(Streams.java:38)
    ... 22 more


Please see attached file for code and line of code where exception occurs



What version of the product are you using? On what operating system?

OS:       Windows 7
JDK:      jdk1.7.0_03
          Eclipse Version: Indigo Service Release 2


Please provide any additional information below.
This is my first time with USSD. Please help as soon as possible

```

Original issue reported on code.google.com by `Mone.Aks...@gmail.com` on 28 Jul 2012 at 2:23

Attachments:
- [Code.txt](https://storage.googleapis.com/google-code-attachments/mchoice-applications/issue-4/comment-0/Code.txt)

**Comment by GoogleCodeExporter** [comment]
```
This is closed use URL which is given there in 
(http://code.google.com/p/mchoice-applications/wiki/JavaGuide#USSD_Guide)
```

Original comment by `Mone.Aks...@gmail.com` on 28 Jul 2012 at 3:07
